version: '3.8'

services:
  inventory-service:
    image: ${IMAGE_NAME}
    container_name: ${IMAGE_NAME}-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8030:8080"
    restart: unless-stopped
